-- =====================================================================
--  SCHEMA DO BANCO DE DADOS - CONTROLE DE PONTO (DIAGONAL INVENTADA)
-- ---------------------------------------------------------------------
--  COMO USAR:
--  1. Abra o painel do Supabase -> SQL Editor
--  2. Cole TODO este arquivo e clique em "Run"
--  3. Pronto! As tabelas e as permissões (RLS) serão criadas/atualizadas.
--
--  Este script é IDEMPOTENTE: pode ser rodado quantas vezes quiser.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) TABELA: funcionarios
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.funcionarios (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo         TEXT NOT NULL,
    matricula             TEXT UNIQUE,
    pin_hash              TEXT,
    cargo                 TEXT DEFAULT 'Funcionário',
    whatsapp              TEXT,
    role                  TEXT NOT NULL DEFAULT 'employee',
    foto_url              TEXT,
    status                BOOLEAN NOT NULL DEFAULT TRUE,
    horario_entrada       TIME NOT NULL DEFAULT '08:00',
    horario_saida         TIME NOT NULL DEFAULT '17:00',
    horario_almoco_inicio TIME DEFAULT '13:00',
    horario_almoco_fim    TIME DEFAULT '14:00',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS horario_almoco_inicio TIME DEFAULT '13:00';
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS horario_almoco_fim    TIME DEFAULT '14:00';
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS cargo TEXT DEFAULT 'Funcionário';
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS horario_entrada TIME NOT NULL DEFAULT '08:00';
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS horario_saida   TIME NOT NULL DEFAULT '17:00';
ALTER TABLE public.funcionarios ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- ---------------------------------------------------------------------
-- 2) TABELA: registros_ponto
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.registros_ponto (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id      BIGINT NOT NULL REFERENCES public.funcionarios(id) ON DELETE CASCADE,
    data_registro       DATE NOT NULL,
    clock_in            TIMESTAMPTZ,
    clock_out           TIMESTAMPTZ,
    inserido_por_admin  BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (funcionario_id, data_registro)
);
ALTER TABLE public.registros_ponto ADD COLUMN IF NOT EXISTS inserido_por_admin BOOLEAN DEFAULT FALSE;
ALTER TABLE public.registros_ponto ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- ---------------------------------------------------------------------
-- 3) TABELA: logs_atividade
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.logs_atividade (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT REFERENCES public.funcionarios(id) ON DELETE SET NULL,
    acao        TEXT,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- 4) ROW LEVEL SECURITY (RLS) E POLÍTICAS
-- ---------------------------------------------------------------------
-- O frontend acessa o banco com a chave ANON (publishable).
-- Por isso as políticas liberam SELECT/INSERT/UPDATE/DELETE para a
-- chave anon. Isto resolve o problema de "não consigo adicionar
-- funcionários".
-- =====================================================================

ALTER TABLE public.funcionarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_funcionarios" ON public.funcionarios;
CREATE POLICY "anon_select_funcionarios"
    ON public.funcionarios FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_funcionarios" ON public.funcionarios;
CREATE POLICY "anon_insert_funcionarios"
    ON public.funcionarios FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_funcionarios" ON public.funcionarios;
CREATE POLICY "anon_update_funcionarios"
    ON public.funcionarios FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_funcionarios" ON public.funcionarios;
CREATE POLICY "anon_delete_funcionarios"
    ON public.funcionarios FOR DELETE TO anon, authenticated USING (true);

ALTER TABLE public.registros_ponto ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_ponto" ON public.registros_ponto;
CREATE POLICY "anon_select_ponto"
    ON public.registros_ponto FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_ponto" ON public.registros_ponto;
CREATE POLICY "anon_insert_ponto"
    ON public.registros_ponto FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_ponto" ON public.registros_ponto;
CREATE POLICY "anon_update_ponto"
    ON public.registros_ponto FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_ponto" ON public.registros_ponto;
CREATE POLICY "anon_delete_ponto"
    ON public.registros_ponto FOR DELETE TO anon, authenticated USING (true);

ALTER TABLE public.logs_atividade ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_logs" ON public.logs_atividade;
CREATE POLICY "anon_select_logs"
    ON public.logs_atividade FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_logs" ON public.logs_atividade;
CREATE POLICY "anon_insert_logs"
    ON public.logs_atividade FOR INSERT TO anon, authenticated WITH CHECK (true);

-- =====================================================================
-- 5) ÍNDICES (performance)
-- =====================================================================
CREATE INDEX IF NOT EXISTS idx_ponto_funcionario ON public.registros_ponto(funcionario_id);
CREATE INDEX IF NOT EXISTS idx_ponto_data       ON public.registros_ponto(data_registro);
CREATE INDEX IF NOT EXISTS idx_func_status      ON public.funcionarios(status);
CREATE INDEX IF NOT EXISTS idx_func_role         ON public.funcionarios(role);

-- =====================================================================
-- FIM DO SCRIPT
-- =====================================================================
